# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80cdc735512a298a360fb85a9a7a50b631d9fc757ec79b7f96e96764a2ce6837bb92d989d7d91d8c7989e0772702751a52f2409c0c5f6e5238b5edec30be1590

test:
  secret_key_base: 1a9791799604ebb2c5d31c0f259ecfa5873ae4007363634d7f2d5f96e565e463a7f8558cb937cca9acc7549c65482689904395044b9f5146fb5bae385c0c4941

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
